### ISSUE TITLE
StopServiceThread causes crash.

### ISSUE THREAD

**Issue by playingoDEERUX** [moien007/ENet.Managed#6]
It causes a crash and does not leave useful information, just that the "Service thread" has stopped.

**Comment by moien007** [comment]
Thanks for reporting for the issue. The current version of this library has plenty of bugs due to the lack of my experience back in the time.

There is a [rework ](https://github.com/moien007/ENet.Managed/tree/rework)branch for the wrapper which you might have the interest to take a look at, unfortunately, it's crashing and I'll investigate.

**Comment by moien007** [comment]
@playingoDEERUX 
New alpha version `4.0.0-alpha` is published on nuget. Threading is now up to the user.

**Comment by playingoDEERUX** [comment]
@moien007 So do I have to manually create a thread now and is thread-safety still implemented?

**Comment by moien007** [comment]
@playingoDEERUX 

> I have to manually create a thread now?

Yes.

> Is thread-safety still implemented?

Unfortunately no, but you can achieve it using `lock`.
